services:
  selenium-hub:
    image: selenium/hub:4.8.0
    container_name: selenium-hub
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4444/wd/hub/status"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "4444:4444"
    networks:
      - mynetwork

  chrome:
    image: selenium/node-chrome:4.8.0
    depends_on:
      selenium-hub:
        condition: service_healthy
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=5
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
    volumes:
      - /dev/shm:/dev/shm  # Prevent Chrome crashes due to limited shared memory
    networks:
      - mynetwork

  firefox:
    image: selenium/node-firefox:4.8.0
    depends_on:
      selenium-hub:
        condition: service_healthy
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=5
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
    volumes:
      - /dev/shm:/dev/shm  # Prevent Firefox crashes due to limited shared memory
    networks:
      - mynetwork

  mysql:
    image: mysql:8.0
    container_name: mysql-A
    environment:
      MYSQL_ROOT_PASSWORD: rootpwd
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpwd
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "testuser", "-ptestpwd"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mynetwork

  test-runner:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      selenium-hub:
        condition: service_healthy
      mysql:
        condition: service_healthy
    environment:
      SELENIUM_HUB_URL: "http://selenium-hub:4444/wd/hub"
      DB_HOST: "mysql"
      DB_PORT: "3306"
      DB_NAME: "testdb"
      DB_USER: "testuser"
      DB_PASSWORD: "testpwd"
    volumes:
      - ./target/screenshots:/app/target/screenshots
      - ./robot-reports:/app/robot-reports
    networks:
      - mynetwork
    command: ["robot", "--outputdir", "robot-reports", "--loglevel", "TRACE", "tests/"]

networks:
  mynetwork:
  {}

volumes:
  mysql-data: