services:
  selenium-hub:
    image: selenium/hub:4.8.0
    ports:
      - '4444:4444'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4444/wd/hub/status"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - testnet

  chrome:
    image: selenium/node-chrome:4.8.0
    depends_on:
      selenium-hub:
        condition: service_healthy
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - testnet

  firefox:
    image: selenium/node-firefox:4.8.0
    depends_on:
      selenium-hub:
        condition: service_healthy
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - testnet

  test-runner:
    build: .
    user: robot
    depends_on:
      - selenium-hub
      - chrome
      - firefox
    volumes:
      - ./:/app:cached
      - robot_reports:/app/robot-reports
      - screenshots:/app/target/screenshots
    networks:
      - testnet

volumes:
  robot_reports:
  screenshots:

networks:
  testnet:
    driver: bridge
