name: Robot Framework UI Automation Tests

on:
  schedule:
    - cron: '30 6 * * *' # daily at 06:30 UTC
  push:
    branches: [main, master, dev, feature]
  pull_request:
    branches: [main, master, dev, feature]

jobs:
  ui-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    env:
      DOCKER_BUILDKIT: 1
      ROBOT_REPORTS: robot-reports

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Docker Compose plugin
        run: |
          sudo apt-get update
          

      - name: Build Docker images
        run: docker compose build --no-cache

      - name: Start Selenium Hub and browser nodes
        run: docker compose up -d

        timeout-minutes: 5

      - name: Wait for Selenium Hub to be ready
        run: |
          echo "⏳ Waiting for Selenium Grid…"
          for i in {1..60}; do
            if curl -s http://localhost:4444/wd/hub/status \
              | grep -Eq '"ready"[[:space:]]*:[[:space:]]*true'; then
              echo "✅ Selenium Grid ready"
              exit 0
            fi
            echo "  still waiting… ($i/60)"
            sleep 3
          done
          echo "❌ Selenium Grid failed to start in time"
          exit 1

      - name: Run Robot Framework tests
        run: |
          echo "🔍 Running Robot Framework tests…"
          mkdir -p "$ROBOT_REPORTS"
          docker compose run --rm test-runner
        continue-on-error: true

      - name: List generated Robot reports
        if: always()
        run: |
          echo "📂 Contents of reports directory:"
          docker compose run --rm robot sh -c 'ls -R ./robot-reports || echo "No reports found."'

      - name: Upload Robot reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: robot-reports
          path: robot-reports/
          retention-days: 7

      - name: Tear down services
        if: always()
        run: docker compose down -v
